//WARNING: This code was auto generated by template compiler, do not modify by hand!
//Generated on 19.10.2015 18:25:57 by NFX.Templatization.TextCSTemplateCompiler at M6-1271

using System; 
using System.Text; 
using System.Linq; 
using System.Collections.Generic; 

namespace WaveTestSite.Pages 
{

 ///<summary>
 /// Welcome page
 ///</summary>
 public  class AboutUs : WaveTestSite.Pages.Master
 {

    
    public override string Title { get {return "About Us at NFX.Wave"; } }


     protected override void DoRender()
     {
       base.DoRender();
        Target.Write( AboutUs._59_S_LITERAL_0 );

     }
    protected override void  renderHeader()
    {
        Target.Write( AboutUs._59_S_LITERAL_1 );

    }
    protected override void  renderBody()
    {
        Target.Write( AboutUs._59_S_LITERAL_2 );
        Target.Write(Target.Encode( DateTime.Now ));
        Target.Write( AboutUs._59_S_LITERAL_3 );
      if (Context.SupportsSession)
  {
     Context.NeedsSession();
     if (!Context.Session.Items.ContainsKey("COUNTER"))
        Context.Session.Items["COUNTER"] = 0;

     var ctr = (int)Context.Session.Items["COUNTER"];
     ctr++;
     Context.Session.Items["COUNTER"] = ctr;


        Target.Write( AboutUs._59_S_LITERAL_4 );
        Target.Write(Target.Encode( ctr ));
        Target.Write( AboutUs._59_S_LITERAL_5 );
      }
        Target.Write( AboutUs._59_S_LITERAL_6 );

    }


     #region Literal blocks content
        private const string _59_S_LITERAL_0 = @"
"; 
        private const string _59_S_LITERAL_1 = @"
 <h1>
     About Us
 </h1> 
"; 
        private const string _59_S_LITERAL_2 = @"
 <p> This page is about us</p> 
 <p> This page is dynamically generated by the application server. </p> 
 <p> It is now "; 
        private const string _59_S_LITERAL_3 = @" </p> 
"; 
        private const string _59_S_LITERAL_4 = @"
   <p> You have visited this page "; 
        private const string _59_S_LITERAL_5 = @" times during this session</p>

"; 
        private const string _59_S_LITERAL_6 = @"


 <a href=""welcome"">Welcome Page</a> |
 <a href=""subtopic/latest"">SubTopic::Latest Page</a>

 <div>
     <p>Please validate who you are by answering the following question:</p>
     <p>What is the result of <strong>van huntret too pluz faiff?</strong></p>
     <img src=""/mvc/tester/captcha"" />

 </div>

<form id=""frmMultipart1"" action=""/mvc/tester/multipartmap"" method=""post"" enctype=""multipart/form-data"">
Customer:     <input type=""text"" name=""CustomerNumber""><br>
File:      <input type=""file"" name=""Picture""> <br>
      <input type=""submit"" value=""Submit"">
</form> 
<hr>
<form id=""frmMultipart2"" action=""/mvc/tester/multipartrow?map=true"" method=""post"" enctype=""multipart/form-data"">
Customer:     <input type=""text"" name=""CustomerNumber""><br>
File:      <input type=""file"" name=""Picture""> <br>
      <input type=""submit"" value=""Submit"">
</form> 



&nbsp;"; 
     #endregion

 }//class
}//namespace
