//WARNING: This code was auto generated by template compiler, do not modify by hand!
//Generated on 19.10.2015 18:25:57 by NFX.Templatization.TextCSTemplateCompiler at M6-1271

using System; 
using System.Text; 
using System.Linq; 
using System.Collections.Generic; 

namespace WaveTestSite.Pages 
{

 ///<summary>
 /// Welcome page
 ///</summary>
 public  class Welcome : WaveTestSite.Pages.Master
 {

    
    public override string Title { get {return "Welcome to NFX.Wave"; } }


     protected override void DoRender()
     {
       base.DoRender();
        Target.Write( Welcome._26_S_LITERAL_0 );

     }
    protected override void  renderHeader()
    {
        Target.Write( Welcome._26_S_LITERAL_1 );

    }
    protected override void  renderBody()
    {
        Target.Write( Welcome._26_S_LITERAL_2 );
        Target.Write(Target.Encode( DateTime.Now ));
        Target.Write( Welcome._26_S_LITERAL_3 );

    }


     #region Literal blocks content
        private const string _26_S_LITERAL_0 = @"
"; 
        private const string _26_S_LITERAL_1 = @"
 <h1>
     Welcome!
 </h1> 
"; 
        private const string _26_S_LITERAL_2 = @"
 <p> This page is dynamically generated by the application server. </p> 
 <p> It is now "; 
        private const string _26_S_LITERAL_3 = @" </p> 
 <a href=""aboutus"">About Us Page</a> |
 <a href=""recordtest"">Record Test Page</a> |
 <a href=""subtopic/latest"">SubTopic::Latest Page</a>
<hr />
<h2>Here is the form that posts into Tester controller:</h2>
<form id=""frm"" action=""/mvc/tester/echo"" method=""post"">
First name: <input type=""text"" name=""firstname""><br>
Last name:  <input type=""text"" name=""lastname"">
    <input type=""submit"" value=""Submit"">
</form> 


<form id=""frmAdd"" action=""/mvc/tester/add"" method=""post"">
A:     <input type=""text"" name=""a""><br>
B:     <input type=""text"" name=""b""><br>
Text:  <input type=""text"" name=""text"">
    <input type=""submit"" value=""Submit"">
</form> 


<button type=""button"" onclick=""doAjax()"" >AJAX Request</button>

<script type=""text/javascript"">

    function doAjax() {
        var xhr = new XMLHttpRequest();
        xhr.open(""POST"", ""/mvc/tester/echo"");
        xhr.setRequestHeader('Content-Type', 'application/json');
        xhr.onreadystatechange = function () {
            if (xhr.readyState == 4 && xhr.status == 200) {
                alert(xhr.responseText);
            }
        }
        xhr.send(""{a: 1, b: 2}"");

    }


</script>
  
&nbsp;"; 
     #endregion

 }//class
}//namespace
